### ISSUE TITLE
Doesn't compile properly on RPi 1 / armv6

### ISSUE THREAD

**Issue by majorz** [balena-io-projects/balena-rust-hello-world#18]
The produced binary is armv7, where it should be armv6 compatible.

Currently on RPi 1/Zero the `rustup-init.sh` script in the Dockerfile.template downloads an armv6 installer, but downloads an armv7 toolchain. The installer is using `libc::uname`, instead of the modified `uname` command.

I think we can make this work by downloading specifying the toolchain directly when we run the `rustup-init.sh` script, e.g. with `--default-toolchain 1.30.0-arm-unknown-linux-gnueabihf`.

This will probably make the uname binary trick we use obsolete, but we will need a similar script to derive the toolchain script with.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_gewb)

**Comment by zrzka** [comment]
ARM builders fix deployed.

**Comment by apiraino** [comment]
Hi, thanks for following up on this!

I had investigated the issue myself (tried to crosscompile for `armv6` = RPi1) and my understanding is that the only good toolchain for crosscompiling for `armv6` is the one suggested [here](https://stackoverflow.com/a/48087233). Plus I had to crosscompile for `armv6` also a couple of dependencies before linking them to the main project.

It would be interesting if you could share (roughly) what has worked for you to make the crosscompilation work.

**Comment by zrzka** [comment]
@apiraino we do not cross compile. We have ARM build servers with ARMv8 CPUs. And because they're backward compatible with ARMv7 and ARMv7 is backward compatible with ARMv6, ... we can use them to run ARMv6 binaries. In other words, in our case, the problem was about `uname` reporting wrong architecture (now correctly reported) & emulation of deprecated CP15 barrier instructions (which we HW exec them now).
